FROM arm32v7/node:11-slim

LABEL maintainer="pabloromeo"

COPY qemu-arm-static /usr/bin/

RUN apt-get update || : && apt-get install python -y

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3500

CMD ["node", "App.js"]

